### ISSUE TITLE
endian

### ISSUE THREAD

**Issue by mumbel** [mumbel/ghidra_i960#3]
What are the endian options here?  So far my only examples are little, is there anything special about big endian, does it do anything weird like big endian instruction / little endian data or vice-versa?

The elf/coff compiles linked from the other issue look like they only support little, are there any public samples to just do quick tests with?

**Comment by mumbel** [comment]
@the6p4c  could you check the latest commit, and/or if you have a sample on the web somewhere, that'd be great

**Comment by the6p4c** [comment]
I've set off auto-analysis now, and it's chugging along nicely. I'll update when it finishes, but things look to be working well. Really appreciate your work.

**Comment by the6p4c** [comment]
Everything looks good! Thanks again 😁
