### ISSUE TITLE
Status on processor module repo vs proposed ghidra i960 tree?

### ISSUE THREAD

**Issue by biggestsonicfan** [mumbel/ghidra_i960#4]
Greetings again,

A friend of mine is switching to Ghidra and we are planning on fully migrating from IDA to Ghidra. I wanted to see what the most up to date way to begin reverse engineering and I see you've made pull requests to the main Ghidra repo with your own [i960 tree](https://github.com/mumbel/ghidra/tree/i960).

Would cloning and building this version of Ghidra be the most promising for i960 RE work?

Thanks as always for your contributions to this defunct architecture! :)

**Comment by mumbel** [comment]
Hey, longtime.

This repo is ahead of the pull request, I really should merge the last couple of changes.  I would suggest just grabbing the newest download and cloning this into <ghidra.zip>/Ghidra/Processors/    There's no java, so no real manual building (just need to restart ghidra if it was running when you cloned) as it builds the SLEIGH portion at runtime when needed.

Let me know how it goes and if you notice any instructions acting up or noticeably bad pseudo-C.

**Comment by biggestsonicfan** [comment]
Cool deal! And thank you for all your hard work on this since the reddit post! Hope to see this fully integrated into Ghidra someday once they accept a pull request!

**Comment by mumbel** [comment]
@cglmrfreeman   pushed a commit.  if you or your friend are still messing around with this, let me know if i broke anything if you try it.

Hopefully not confusing myself, but did find a few bugs in various places.
Trying to improve stack frame and stack pointer handling, but no improvement that I can tell, just hoping I didn't make it worse.
Added a few more pcodeops to fill in a few unimpl instructions, not going to give great decompiler results, but at least doesn't kill it.

I was trying to get a better handle on the register sets.  I think just assume 0 cache entries available and always write to the stack, but for now I can't get the decompiler to ignore saving the set on a call/callx, which just made for awful pseudo C.  Do things try to read the register sets often/ever? or mostly not worth worrying about in this sort of setup/static analysis

**Comment by biggestsonicfan** [comment]
While I personally haven't migrated to Ghidra yet my friend has been using it to analyze House of the Dead code and has implemented some fixes to the game already. Once I get a better understanding of Ghidra and how to map memory to files then yeah, I'm going to be giving it a deep dive.

And what do you mean by " Do things try to read the register sets often/ever?" Because I'm pretty sure that was the fastest way of moving and analyzing and manipulating data for the i960, at least by looking at my IDA disassembly. It looks like almost everything is passed through a register and read.

**Comment by mumbel** [comment]
Very cool, just googled and found his twitter post.  

Sorry that wasn't clear, still learning the processor here and there.

I just meant have you come across any instructions/code flows in ida/ghidra where saving/restoring local registers on the stack vs in a cache mattered for your analysis.  For example a processor would have ~4 register sets that it can cache (still saving space on that stack, but not saved/written there until a flushreg) and on the 5th call it would have to allocate and write onto the stack... is that something you'd even notice, if it were 0 or 4 cache (not real world, just analysis/RE).

Yeah, ghidra can be an acquired taste, I really like the built-in collaboration, open source aspect, and learning/writing processor modules has been interesting too (I have IDA/hexrays through work).  At the very least competition is a good thing.

**Comment by biggestsonicfan** [comment]
I don't think anything like that ever happens that I've seen.

Also I am hoping to use the built-in collaboration with Sonic the Fighters with another researcher, though I have zero knowledge of how that would work, lol.

**Comment by mumbel** [comment]
I know there is a public ghidra server, not sure who they are/what their rules are/what their incentive is/etc..., (https://www.ghidra-server.org).  Or if you can setup a server on an internet facing machine, its really not too bad to setup a ghidra server.  There is an official guide in the ghidra/docs, but I've also seen at least two other walkthroughs on youtube and a blog.
