### ISSUE TITLE
Debug file parsing

### ISSUE THREAD

**Issue by Decryptortuning** [mumbel/ghidra_i960#9]
[p521v79_int.zip](https://github.com/mumbel/ghidra_i960/files/10346293/p521v79_int.zip)
Have you run across this format before? I have several of these oddball output files.

**Comment by mumbel** [comment]
No I haven't come across the file extension before, sorry.  `file` says `amd 29k coff archive` and the header has `PowerPC`.

**Comment by biggestsonicfan** [comment]
I saw my notifications and I got all excited...

**Comment by mumbel** [comment]
@Decryptortuning I'm semi curious why this was posted here.  Are you thinking these are i960 binaries or just an unknown.  That said I could could add basic support for a29k, but not gonna be much more more than what you can provide or add debug for.  The coff seems significantly different in either case.  I960 had enough difference itself in coff format that I kinda of just passed on that too,.... Java is not my thing.  I really like the ISA portion, but not past that. (I960 is not a passion project so I haven't done any deep dives)

**Comment by mumbel** [comment]
@biggestsonicfan  I understand, I'm sorry.  I did take a look, but it was more than I wanted to undertake, and only getting worse for IRL reasons

**Comment by biggestsonicfan** [comment]
@mumbel No worries, always more important to take care of the irl stuff! I was just hoping there were more people looking at i960 binaries and I could snoop their uploads but it's too bad this turned out to be unrelated.

**Comment by Decryptortuning** [comment]
@mumbel My apologies, I had a brainfart and these are IEEE-695 files, my apologies!

**Comment by mumbel** [comment]
Ahh, I did see a random forum mentioning that this could be coff or that format, but the forum made it sound like that was a packaging issue.  They were i960 binaries?

**Comment by mumbel** [comment]
@Decryptortuning if you are interested I did knock out a very quick attempt at a29k... But the compile spec is broken so as of now is just a dissembler.  Still reading up on calling convention and shoving that into ghidra xml

**Comment by Decryptortuning** [comment]
@mumbel I Found this very recent project for parsing I-695 object files. https://www.cocoacrumbs.com/blog/2023-01-01-reading-zilogs-lod-file-format/
https://bitbucket.org/cocoacrumbselectronics/ieee-695-reader/src/master/
My files are actually tricore or PPC in this stupid i-695 format, just need to parse the object file and load it.

**Comment by Decryptortuning** [comment]
@mumbel Also see this
https://github.com/alisw/gcc-toolchain/blob/master/binutils-2.25.1/binutils/ieee.c

**Comment by biggestsonicfan** [comment]
Guess we can go ahead and close this then, lol.
